### ISSUE TITLE
Missing  Gopkg.toml

### ISSUE THREAD

**Issue by jzielke84** [camptocamp/terraform-provider-pass#30]
After running the `go get ...` command and changing into the `terraform-provider-pass`dir, the `dep ensure`command returns:

```
could not find project Gopkg.toml, use dep init to initiate a manifest
```
 Any solutions?

**Comment by phillipj** [comment]
The README needs to be updated with new build instructions and go version
after go modules was introduced in:
https://github.com/camptocamp/terraform-provider-pass/commit/41a2cf243c74ef99c31352728a7750bfa5b9e970

**Comment by jzielke84** [comment]
OK, yes that would be nice if someone does that since I'm stuck here with an updated terraform/terragrunt environment which tells me that the pass-module i have installed is outdated and cannot be used.

**Comment by phillipj** [comment]
Have you tried any of the binaries available on the releases page?
https://github.com/camptocamp/terraform-provider-pass/releases

**Comment by jzielke84** [comment]
> Have you tried any of the binaries available on the releases page? https://github.com/camptocamp/terraform-provider-pass/releases
Oh no, not yet, thanks for pointing that out. I'll try them out later :-)

**Comment by jzielke84** [comment]
@phillipj OK I've tried the download from the builds page and copied it into the corresponding plugin dir. Now I get `Provider "pass" not available for installation`. This is quite confusing since it has been working flawlessly before.

**Comment by phillipj** [comment]
Did you sort this out? Looking at this issue in github.com now, your last
couple of replies from today aren't present anymore?

**Comment by jzielke84** [comment]
@phillipj 

Yes, I had to rename the file to "terraform-provider-pass" and then it was detected correctly by terragrunt. There's so much happening on the terraform project and I had to change much since the update to version 0.12.x. I'm not sure whether terraform is ready for production yet, since so many things get changed frequently and the guys at terragrunt always have to fix things up.

Also I had to change the password store dir variable from get_terragrunt_dir()/my/dir to ${get_terragrunt_dir()}/my/dir.

**Comment by phillipj** [comment]
> There's so much happening on the terraform project and I had to change much since the update to version 0.12.x. I'm not sure whether terraform is ready for production yet, since so many things get changed frequently and the guys at terragrunt always have to fix things up.

I can relate to what you're describing! Personally haven't considered `terragrunt` before, but the upgrade from `terraform` v0.11 to v0.12 was a big one. Although I must say the migration was quite painless in the projects I've done it in, primarily because the added `terraform 0.12upgrade` command.

Really appreciate `terraform` for small/medium sized projects, certainly see it as production ready for those kinds of projects. Things can get very hairy in big projects, though I'm not entirely sure it's due to `terraform` (or any infra-as-code tool), but rather the fact that turning a large infrastructure up-side-down will get painful anyways.

Sooo that means this issue can be closed? :)
